theme: minimal-mistakes-jekyll
repository: jamesstout/jamesstout.github.io
minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
name: &NAME "stouty.xyz"
title: *NAME
title_separator: "|"
description: "James Stout. CTO. iOS. Web developer. Flatliner. Tech, crypto, comedy, Hong Kong, #hcafc, smashing telly and, of course, the weather."
url: "https://stouty.xyz"

search: true
# search_provider: lunr
show_dir_listing: false

search_provider: algolia

algolia:
  application_id         : TE1537XNZ4
  index_name             : stouty.xyz
  search_only_api_key    : c3967c693f4a1d3ca8ed221f259c6a5f
  powered_by             : true
  files_to_exclude       :
    - categories/*.html
    - tags/*.html
    - year-archive/*.html
    - page*/*.html
    - page*/
    - piwik/
    - year-archive/
    - tags/
    - categories/
    - index.html
    - 404.html
  settings:
    attributesForFaceting:
      - type
      - searchable(categories)
      - searchable(tags)
      - searchable(title)
    searchableAttributes:
      - title
      - unordered(content)
      - collection,categories,tags
    attributesToHighlight:
      - title
      - content
      - html
      - categories
      - tags
    highlightPreTag: '<em class="custom_highlight">'
    highlightPostTag: '</em>'

twitter:
  username: "stoutyhk"

# Site Author
author:
  name             : "James Stout"
  avatar           :  # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "CTO. iOS/Web developer. Flatliner. Tech, crypto, comedy, Hong Kong, #hcafc, smashing telly and, of course, the weather"
  location         : "Hong Kong"
  email            : 
  # uri              : https://www.zoooot.xyz
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        : stouty
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  feedio           : http://www.feedio.co/@stoutyhk?came_from=homepagefeedbutton
  foursquare       :
  github           : jamesstout
  gitlab           :
  google_plus      :
  keybase          : stouty
  instagram        : 
  lastfm           : stoutyhk
  linkedin         : # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          : stoutyhk
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"

# Reading Files
include:
  - _pages
  - _redirects
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - Gemfile
  - Gemfile.lock
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
  - /misc
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Analytics
analytics:
  provider               : google-gtag # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : UA-121620384-1

# google_site_verification: 1090wZmdhUfoCKnEqVFawGTa6AKwbN_vmrw-H6Y7aSE
# bing_site_verification: 33DDEA42FFE3F60411C72F8B34B31973

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: pretty
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Hong_Kong

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

future: true

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-typogrify
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - premonition

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-typogrify
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - premonition

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# github: [metadata]
# github:
#     repository_url: https://github.com/jamesstout/jamesstout.github.io

# comments:
#   provider: "disqus"
#   disqus:
#     shortname: "stouty-xyz"

# exclude: [misc]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      layout: single
      author_profile: true
      share: false
      related: true
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/files"
    values:
        image: true
