theme: minimal-mistakes-jekyll
repository: jamesstout/jamesstout.github.io
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
name: &NAME "James Stout"
title: *NAME
title_separator: "|"
description: "A flexible Jekyll theme for your blog or site with a minimalist aesthetic."
url: "https://jamesstout.github.io/"

search: true
search_provider: lunr
show_dir_listing: false
include: ["_pages"]

twitter:
  username: "stoutyhk"

# Site Author
author:
  #name             : *NAME
  avatar           :  # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "iOS/web developer. Flatliner. Tech, crypto, comedy, Hong Kong, #hcafc, smashing telly and, of course, the weather"
  location         : "Hong Kong"
  email            : 
  uri              :
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        : stouty
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : jamesstout
  gitlab           :
  google_plus      :
  keybase          : stouty
  instagram        : 
  lastfm           : stoutyhk
  linkedin         : # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          : stoutyhk
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: pretty
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Hong_Kong

# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-typogrify
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-typogrify
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# github: [metadata]
# github:
#     repository_url: https://github.com/jamesstout/jamesstout.github.io


exclude: [misc]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      comments: true
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: false
      related: true
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/files"
    values:
        image: true
